### ISSUE TITLE
option to customize modified check

### ISSUE THREAD

**Issue by matthewmueller** [makojs/stat#1]
i'm assuming that this was built so you could do incremental builds in middleware, but one thing i'd like to bring back is the `duo.json`-like mapping for incremental builds across processes. 

i think one way to support this without making any assumptions is to allow you to modify how the `modified` check is made.

**Comment by dominicbarnes** [comment]
The more I think about it, I think this is best done with a separate plugin. I really want to encourage more plugins that fill roles for different workflows.

For cases where plugins are composed together, I would prefer a pattern of disabling specific plugins via configuration so you can use custom ones. (like the `options.read` and `options.write` in the browser plugin)

**Comment by matthewmueller** [comment]
Okay cool. Yah that makes sense
